pipeline {
    agent any
    
//     environment {
//     	APP_SUBFOLDER = 'FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface'
//     }
    
//     stages {
//         stage('Clean-up') {
//             steps {
// //                 bat 'del %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\fpso_interface.spec'
// //                 bat 'del %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\fpso_interface.zip'
// //                 bat 'rmdir /s /q %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\__pycache__'
//                 bat 'rmdir /s /q %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\build'
//                 bat 'rmdir /s /q %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\dist'
//             }
//         }
        
        stage('Build') {
            steps {
                bat 'python %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%\\build.py %FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface%'
            }
        }
        
        stage('Deliver') {
            steps {
              script {
                zip zipFile: 'FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface' + '\\fpso_interface.zip', archive: false, dir:  + '\\dist\\fpso_interface'
                }
            post {
                success {
                    archiveArtifacts 'FPSO_Energy_Analytics\\FPSO_Solucao\\Front_end\\FPSO_Interface' + '\\fpso_interface.zip'
                }
            }
            }
        }
    }
}
